name: BuildDeployBotToWebApp

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6'                 # set this to the .NET Core version to use

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Resource group of the Azure Web App hosting the Azure AI bot'
        required: true
        default: Telephony.Automated.Rg
      webAppName:
        description: 'Azure Web App Name'
        required: true
        default: automatedbot20250106

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build ./acs/src/AIBot/AIBot.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./acs/src/AIBot/AIBot.csproj -c Release -o ${{env.DOTNET_ROOT}}/AIBot

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: AIBot
          path: ${{env.DOTNET_ROOT}}/AIBot

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: AIBot

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.webAppName }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
