name: DeployIAC

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # deploy-iac
  deploy-iac:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: 'Login via Azure CLI'
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - shell: bash
       run: |
            # Find all Solution.xml files in the solution directory and its subdirectories
            chmod +x ./acs/deploy.sh
            cd acs
            ./deploy.sh

